swagger: "2.0"
info:
  version: "1.0.0"
  title: Exemple d'API CRUD
  description: API de démonstration avec les méthodes GET, POST, PUT, DELETE

host: localhost:3000
basePath: /api
schemes:
  - http

paths:
  /users:
    get:
      summary: Récupérer tous les utilisateurs
      responses:
        200:
          description: Succès
    post:
      summary: Créer un nouvel utilisateur
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        201:
          description: Utilisateur créé

  /users/{id}:
    get:
      summary: Récupérer un utilisateur par ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        200:
          description: Utilisateur trouvé
        404:
          description: Utilisateur non trouvé

    put:
      summary: Mettre à jour un utilisateur
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: user
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        200:
          description: Utilisateur mis à jour
        404:
          description: Utilisateur non trouvé

    delete:
      summary: Supprimer un utilisateur
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        204:
          description: Supprimé avec succès
        404:
          description: Utilisateur non trouvé
